-- ============================================================================
-- LiveLab: TAP and ESS role-based access setup
--
-- Run this script once in SQL Workshop > SQL Scripts as the schema that owns
-- TMS_EMPLOYEES. It creates the role tables, seeds the four lab roles and demo
-- employees, assigns one role to each demo employee, and prepares the local
-- lab credentials. The role tables and TMS_EMPLOYEES.PASSWORD column must not
-- already exist in the schema.
--
-- Prerequisites:
--   * TMS_EMPLOYEES with EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, JOB_ID,
--     DEPT_ID, and STATUS columns.
--   * The sample job IDs 1, 4, and 5 and department IDs 2 and 3 used below
--     exist in the TMS sample data. Change those IDs if your seed data differs.
--
-- The demo addresses use the reserved .example domain. Existing rows matching
-- those addresses are deliberately refreshed as active lab accounts. All
-- active employees receive the lab password "apex". Oracle commits DDL
-- implicitly, so this is a one-time setup script rather than one transaction
-- that can be rolled back as a whole.
-- ============================================================================

-- The authentication steps in this LiveLab use STANDARD_HASH and do not need
-- DBMS_CRYPTO. If customized code calls DBMS_CRYPTO, a DBA can grant it
-- separately to the APEX parsing schema (replace APEX_LL if needed):
-- GRANT EXECUTE ON SYS.DBMS_CRYPTO TO APEX_LL;

-- Create the role lookup table.
CREATE TABLE tms_roles (
  role_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
  role_code VARCHAR2(30)  NOT NULL,
  role_name VARCHAR2(100) NOT NULL,
  is_active NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT pk_tms_roles PRIMARY KEY (role_id),
  CONSTRAINT uq_tms_roles_code UNIQUE (role_code),
  CONSTRAINT ck_tms_roles_active CHECK (is_active IN (0, 1))
);

-- Create the employee-to-role mapping table. The composite primary key
-- permits one row per employee and role.
CREATE TABLE tms_employee_roles (
  employee_id NUMBER        NOT NULL,
  role_id     NUMBER        NOT NULL,
  assigned_on TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  assigned_by VARCHAR2(255),
  is_active   NUMBER(1)     DEFAULT 1 NOT NULL,
  CONSTRAINT pk_tms_employee_roles
    PRIMARY KEY (employee_id, role_id),
  CONSTRAINT fk_ter_employee
    FOREIGN KEY (employee_id)
    REFERENCES tms_employees (employee_id),
  CONSTRAINT fk_ter_role
    FOREIGN KEY (role_id)
    REFERENCES tms_roles (role_id),
  CONSTRAINT ck_ter_is_active
    CHECK (is_active IN (0, 1))
);

CREATE INDEX ix_ter_role
  ON tms_employee_roles (role_id);

-- Seed the role catalog without duplicating role codes.
MERGE INTO tms_roles target
USING (
  SELECT 'RECRUITER' AS role_code, 'Recruiter' AS role_name FROM dual
  UNION ALL
  SELECT 'HR_ADMIN', 'HR Admin' FROM dual
  UNION ALL
  SELECT 'HIRING_MANAGER', 'Hiring Manager' FROM dual
  UNION ALL
  SELECT 'TA_ADMIN', 'TA Admin' FROM dual
) source
ON (target.role_code = source.role_code)
WHEN MATCHED THEN
  UPDATE SET target.role_name = source.role_name,
             target.is_active = 1
WHEN NOT MATCHED THEN
  INSERT (role_code, role_name, is_active)
  VALUES (source.role_code, source.role_name, 1);

-- Seed or refresh the four reserved demo accounts. They must be Active because
-- Lab 1 prepares credentials only for active employees.
MERGE INTO tms_employees target
USING (
  SELECT 'maya.patel@acme.example' AS email,
         'Maya' AS first_name,
         'Patel' AS last_name,
         5 AS job_id,
         3 AS dept_id
    FROM dual
  UNION ALL
  SELECT 'arjun.mehta@acme.example', 'Arjun', 'Mehta', 4, 3 FROM dual
  UNION ALL
  SELECT 'olivia.brown@acme.example', 'Olivia', 'Brown', 1, 2 FROM dual
  UNION ALL
  SELECT 'liam.wilson@acme.example', 'Liam', 'Wilson', 4, 3 FROM dual
) source
ON (UPPER(TRIM(target.email)) = UPPER(source.email))
WHEN MATCHED THEN
  UPDATE SET target.first_name = source.first_name,
             target.last_name  = source.last_name,
             target.job_id     = source.job_id,
             target.dept_id    = source.dept_id,
             target.status     = 'Active'
WHEN NOT MATCHED THEN
  INSERT (
    first_name, last_name, email, job_id, dept_id, status
  )
  VALUES (
    source.first_name, source.last_name, source.email,
    source.job_id, source.dept_id, 'Active'
  );

-- Assign each demo account its workshop persona. Existing mappings are
-- reactivated without changing their original assignment timestamp.
MERGE INTO tms_employee_roles target
USING (
  SELECT e.employee_id,
         r.role_id
    FROM (
      SELECT 'maya.patel@acme.example' AS email,
             'RECRUITER' AS role_code
        FROM dual
      UNION ALL
      SELECT 'arjun.mehta@acme.example', 'HR_ADMIN' FROM dual
      UNION ALL
      SELECT 'olivia.brown@acme.example', 'HIRING_MANAGER' FROM dual
      UNION ALL
      SELECT 'liam.wilson@acme.example', 'TA_ADMIN' FROM dual
    ) demo
    JOIN tms_employees e
      ON UPPER(TRIM(e.email)) = UPPER(demo.email)
    JOIN tms_roles r
      ON r.role_code = demo.role_code
) source
ON (target.employee_id = source.employee_id
    AND target.role_id = source.role_id)
WHEN MATCHED THEN
  UPDATE SET target.is_active = 1,
             target.assigned_by = COALESCE(
               target.assigned_by,
               SYS_CONTEXT('USERENV', 'SESSION_USER')
             )
WHEN NOT MATCHED THEN
  INSERT (employee_id, role_id, assigned_by, is_active)
  VALUES (
    source.employee_id,
    source.role_id,
    SYS_CONTEXT('USERENV', 'SESSION_USER'),
    1
  );

-- Prepare the local lab credential. The authentication code in this workshop
-- uses STANDARD_HASH, so no DBMS_CRYPTO grant is required.
ALTER TABLE tms_employees ADD password VARCHAR2(80);

CREATE OR REPLACE FUNCTION hash_password (
  p_user_name IN VARCHAR2,
  p_password  IN VARCHAR2
) RETURN VARCHAR2
IS
  l_salt     CONSTANT VARCHAR2(255) := '2345USFGOJN2T3HW89EFGOBN23R5SDFGAKL';
  l_password VARCHAR2(64);
BEGIN
  SELECT STANDARD_HASH(
           p_password || SUBSTR(l_salt, 4, 14) || UPPER(p_user_name) || SUBSTR(l_salt, 5, 10),
           'SHA256'
         )
    INTO l_password
    FROM dual;

  RETURN l_password;
END hash_password;
/

UPDATE tms_employees
   SET password = hash_password(UPPER(email), 'apex')
 WHERE status = 'Active';

COMMIT;
